<?php

declare(strict_types=1);

namespace Stadly\PasswordPolice\WordList;

use ErrorException;
use InvalidArgumentException;
use RuntimeException;
use Stadly\PasswordPolice\CaseConverter\CaseConverterInterface;

final class Pspell implements WordListInterface
{
    /**
     * @var int Pspell dictionary.
     */
    private $pspell;

    /**
     * @var CaseConverterInterface[] Case converters.
     */
    private $caseConverters;

    /**
     * Pspell dictionaries are case-sensitive.
     * Specify case converters if tests should also be performed for the word converted to other cases.
     *
     * @param int $pspell Pspell dictionary link, as generated by `pspell_new` and friends.
     * @param CaseConverterInterface... $caseConverters Case converters.
     */
    public function __construct(int $pspell, CaseConverterInterface... $caseConverters)
    {
        $this->pspell = $pspell;
        $this->caseConverters = $caseConverters;
    }

    /**
     * Pspell dictionaries are case-sensitive.
     * Specify case converters if tests should also be performed for the word converted to other cases.
     *
     * @param string $locale Locale of the pspell dictionary to load. For example `en-US` or `de`.
     * @param CaseConverterInterface... $caseConverters Case converters.
     * @throws RuntimeException If the pspell dictionary could not be loaded.
     * @return self Pspell word list.
     */
    public static function fromLocale(string $locale, CaseConverterInterface... $caseConverters): self
    {
        if (preg_match('{^[a-z]{2}(?:[-_][A-Z]{2})?$}', $locale) !== 1) {
            throw new InvalidArgumentException(sprintf('%s is not a valid locale.', $locale));
        }

        set_error_handler([self::class, 'errorHandler']);
        try {
            $pspell = pspell_new($locale);
        } catch (ErrorException $exception) {
            throw new RuntimeException('An error occurred while loading the word list.', /*code*/0, $exception);
        } finally {
            restore_error_handler();
        }

        assert($pspell !== false);

        return new self($pspell, ...$caseConverters);
    }

    /**
     * {@inheritDoc}
     */
    public function contains(string $word): bool
    {
        foreach ($this->getWordsToCheck($word) as $wordVariant) {
            set_error_handler([self::class, 'errorHandler']);
            try {
                $check = pspell_check($this->pspell, $wordVariant);
            } catch (ErrorException $exception) {
                throw new RuntimeException('An error occurred while using the word list.', /*code*/0, $exception);
            } finally {
                restore_error_handler();
            }

            if ($check) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return string[] Variants of the word to check.
     */
    private function getWordsToCheck(string $word): array
    {
        $words = [$word];

        foreach ($this->caseConverters as $caseConverter) {
            $words[] = $caseConverter->convert($word);
        }

        return array_unique($words);
    }

    /**
     * @throws ErrorException Error converted to an exception.
     */
    private static function errorHandler(int $severity, string $message, string $filename, int $line): void
    {
        throw new ErrorException($message, /*code*/0, $severity, $filename, $line);
    }
}
